### ISSUE TITLE
TypeError: new(): invalid data type 'str'

### ISSUE THREAD

**Issue by hoangftran** [daominhkhanh20/VietnameseSpellingCorrection#2]
When I train the model by running `python train.py` I got error:

Please help!

**Comment by daominhkhanh20** [comment]
I preprocess all text to int before training model because I want to reduce time for convert text to int

**Comment by hoangftran** [comment]
I have no idea. Can you show me how to fix this error?

**Comment by daominhkhanh20** [comment]
As you can see, **torch tensor requires int, not str**, because before I trained the model, I calculate all word ids, error ids,... . You can read my code in dataloader

**Comment by hoangftran** [comment]
Hi sir, thank you for your answer. When I training I have another problem: **ValueError**: Expected input batch_size (3072) to match target batch_size (3200).
![image](https://user-images.githubusercontent.com/47239029/144784738-2b4685f1-3713-4b78-bd64-35b0bc1024b9.png)
This error happens after training about 3 epochs, may be something wrong when I preprocess the data.
Can you show me why this happen and how to fix this? Thank you very much and have a nice day!
